local M = {}
M.BOARD_COLUMNS = 20
M.BOARD_ROWS = 20

M.URL_SCENE_TILEMAP = "/scene#scene"

M.LAYER_ROOM_CELL = "room_cell"
M.LAYER_CHARACTER = "character"

M.TILE_GRASS = 1
M.TILE_HERO = 2
M.TILE_WEASEL = 3

M.DIRECTION_UP = "up"
M.DIRECTION_RIGHT = "right"
M.DIRECTION_DOWN = "down"
M.DIRECTION_LEFT = "left"

M.ACTION_UP = "UP"
M.ACTION_DOWN = "DOWN"
M.ACTION_LEFT = "LEFT"
M.ACTION_RIGHT = "RIGHT"
M.ACTION_GREEN = "GREEN"
M.ACTION_RED = "RED"
return M